spring:
  mqtt:
    urls:
      - tcp://193.112.42.141:1883
    username: admin
    password: public
    producer-id: producerId
    consumer-id: consumerId
    default-topic: hello
    consumerTopics:
      - hello
      - login